export const siteUrl = 'https://www.pestcontrolkochi.com';

export const pageMetadata = {
  homepage: {
    title: 'Eco Pest India - Best Pest Control Services in Kochi, Kerala',
    description: 'Professional, eco-friendly pest control services in Kochi. Termite, bed bug, cockroach control with 25+ years experience. Free inspection & 5-year warranty.',
    canonical: '/',
    ogImage: '/images/og-homepage.jpg',
    keywords: 'pest control, pest control kochi, termite control kochi, pest control ernakulam, eco pest india',
    lastModified: '2026-08-05',
    changefreq: 'daily',
    priority: '1.0',
  },
  'pest-control-kochi': {
    title: 'Professional Pest Control Kochi - Eco Pest India | 25+ Years Experience',
    description: 'Top-rated pest control in Kochi for termites, cockroaches, bed bugs & rodents. Family-safe, eco-friendly treatments with up to 5-year warranty. Same-day inspections available.',
    canonical: '/pest-control-kochi',
    ogImage: '/images/og-pest-control-kochi.jpg',
    keywords: 'pest control kochi, best pest control kochi, pest control ernakulam, termite control kochi',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.9',
  },
  about: {
    title: 'About Eco Pest India - Trusted Pest Control in Kochi',
    description: 'Learn how Eco Pest India delivers safe, eco-friendly pest control across Kochi through experienced technicians and local service.',
    canonical: '/about',
    ogImage: '/images/og-about.jpg',
    keywords: 'about eco pest india, pest control company kochi, pest control history',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.6',
  },
  services: {
    title: 'Pest Control Services in Kochi - Eco Pest India',
    description: 'Complete pest control services in Kochi for homes, offices, restaurants, and warehouses. Termite, cockroach, rodent, bed bug, mosquito control and more.',
    canonical: '/services',
    ogImage: '/images/og-services.jpg',
    keywords: 'pest control services kochi, termite control kokhi, cockroach control kochi',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.8',
  },
  locations: {
    title: 'Pest Control Locations in Kochi - Eco Pest India',
    description: 'Serving Kochi and Ernakulam with local pest control across Kakkanad, Edappally, Aluva, Kalamassery and surrounding neighborhoods.',
    canonical: '/locations',
    ogImage: '/images/og-locations.jpg',
    keywords: 'pest control locations kochi, pest control kakkanad, pest control edappally',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.8',
  },
  faq: {
    title: 'Pest Control FAQ - Kochi Termite, Rodent, Cockroach Questions',
    description: 'Frequently asked questions about pest control in Kochi, termite treatment, rodents, cockroaches, bed bugs, and safety.',
    canonical: '/faq',
    ogImage: '/images/og-faq.jpg',
    keywords: 'pest control faq kochi, termite control questions, rodent control faq',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.6',
  },
  contact: {
    title: 'Contact Eco Pest India - Kochi Pest Control Experts',
    description: 'Contact Eco Pest India for fast pest control inspections, quotes and support across Kochi and Ernakulam.',
    canonical: '/contact',
    ogImage: '/images/og-contact.jpg',
    keywords: 'contact eco pest india, pest control inquiry kochi, pest control quote',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.7',
  },
  privacy: {
    title: 'Privacy Policy - Eco Pest India',
    description: 'Privacy policy for Eco Pest India, covering pest control inquiries, customer data protection, and website usage.',
    canonical: '/privacy',
    ogImage: '/images/og-privacy.jpg',
    keywords: 'privacy policy, eco pest india privacy, pest control site privacy',
    lastModified: '2026-08-05',
    changefreq: 'yearly',
    priority: '0.3',
  },
  terms: {
    title: 'Terms of Service - Eco Pest India',
    description: 'Terms of service for using Eco Pest India online resources and requesting pest control services in Kochi.',
    canonical: '/terms',
    ogImage: '/images/og-terms.jpg',
    keywords: 'terms of service, pest control terms, eco pest india terms',
    lastModified: '2026-08-05',
    changefreq: 'yearly',
    priority: '0.3',
  },
  'termite-control-kochi': {
    title: 'Termite Control Kochi - Expert Termite Treatment & Prevention',
    description: 'Powerful termite control in Kochi using Drill-Fill-Seal, pre-construction barriers, and moisture management. Same-day inspections and warranty available.',
    canonical: '/termite-control-kochi',
    ogImage: '/images/og-termite-kochi.jpg',
    keywords: 'termite control kochi, termite treatment kochi, drill fill seal kochi',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.85',
  },
  'cockroach-control-kochi': {
    title: 'Cockroach Control Kochi - Safe Gel Baiting & Sanitation',
    description: 'Fast cockroach control in Kochi with safe gel baiting, source elimination, and prevention for kitchens and homes.',
    canonical: '/cockroach-control-kochi',
    ogImage: '/images/og-cockroach-kochi.jpg',
    keywords: 'cockroach control kochi, roach treatment kochi, kitchen pest control',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.85',
  },
  'rodent-control-kochi': {
    title: 'Rodent Control Kochi - Rat & Mouse Exclusion Services',
    description: 'Rodent control in Kochi for homes, offices and warehouses with exclusion, baits, and monitoring.',
    canonical: '/rodent-control-kochi',
    ogImage: '/images/og-rodent-kochi.jpg',
    keywords: 'rodent control kochi, rat control kochi, mice control kochi',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.8',
  },
  'mosquito-control-kochi': {
    title: 'Mosquito Control Kochi - Larvicidal & Residual Spraying',
    description: 'Mosquito control in Kochi with eco-safe larvicides, residual sprays, and breeding site elimination.',
    canonical: '/mosquito-control-kochi',
    ogImage: '/images/og-mosquito-kochi.jpg',
    keywords: 'mosquito control kochi, dengue prevention kochi, mosquito fogging kochi',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.8',
  },
  'bed-bug-control-kochi': {
    title: 'Bed Bug Control Kochi - Thermal Treatment & Follow-up',
    description: 'Discreet bed bug treatment in Kochi for homes, hotels, and rentals with thermal and chemical protocols.',
    canonical: '/bed-bug-control-kochi',
    ogImage: '/images/og-bed-bug-kochi.jpg',
    keywords: 'bed bug control kochi, bed bug treatment kochi, mattress pest control',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.8',
  },
  'bee-control-kochi': {
    title: 'Bee & Wasp Control Kochi - Safe Removal and Relocation',
    description: 'Professional bee and wasp nest removal in Kochi with safety-first relocation and perimeter treatment.',
    canonical: '/bee-control-kochi',
    ogImage: '/images/og-bee-kochi.jpg',
    keywords: 'bee control kochi, wasp nest removal kochi, insect control kochi',
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.75',
  },
  'pest-control-aluva': {
    title: 'Pest Control Aluva - Eco Pest India',
    description: 'Local pest control services in Aluva, Ernakulam with safe termite, rodent, and cockroach treatment.',
    canonical: '/pest-control-aluva',
    ogImage: '/images/og-aluva.jpg',
    keywords: 'pest control aluva, pest control ernakulam, termite control aluva',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.75',
  },
  'pest-control-kakkanad': {
    title: 'Pest Control Kakkanad - Eco Pest India',
    description: 'Top rated pest control in Kakkanad for residential and commercial spaces with local technical expertise.',
    canonical: '/pest-control-kakkanad',
    ogImage: '/images/og-kakkanad.jpg',
    keywords: 'pest control kakkanad, pest control kochi, service kakkanad',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.75',
  },
  'pest-control-edappally': {
    title: 'Pest Control Edappally - Eco Pest India',
    description: 'Reliable pest control in Edappally for termite, cockroach, mosquito, and rodent management.',
    canonical: '/pest-control-edappally',
    ogImage: '/images/og-edappally.jpg',
    keywords: 'pest control edappally, pest control kochi, termite control edappally',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.75',
  },
  'pest-control-kalamassery': {
    title: 'Pest Control Kalamassery - Eco Pest India',
    description: 'Specialised pest control in Kalamassery with eco-friendly treatments and fast local response.',
    canonical: '/pest-control-kalamassery',
    ogImage: '/images/og-kalamassery.jpg',
    keywords: 'pest control kalamassery, pest control kochi, eco pest india',
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.75',
  },
};

export const defaultPageData = {
  title: 'Eco Pest India - Trusted Pest Control in Kochi',
  description: 'Professional pest control services in Kochi, Ernakulam, and Kerala. Safe termite, rodent, cockroach, mosquito, and bed bug control.',
  canonical: '/',
  ogImage: '/images/1.jpeg',
  keywords: 'pest control kochi, pest control ernakulam, termite control',
};
