export const siteUrl = 'https://www.pestcontrolkochi.com';

export const pageMetadata = {
  homepage: {
    title: 'Eco Pest India - #1 Trusted Pest Control Services in Kochi, Kerala',
    description: 'India\'s most trusted pest control company in Kochi. 29+ years of expertise in termite, cockroach, bed bug & rodent control. Free inspection, 5-year warranty, 4.9★ rating.',
    canonical: '/',
    ogTitle: 'Eco Pest India - Professional Pest Control Services in Kochi',
    ogDescription: 'Family-safe, eco-friendly pest control in Kochi. WHO-approved chemicals. Same-day service. Up to 10-year warranty. 4,800+ happy customers.',
    ogImage: '/images/og-homepage.jpg',
    ogType: 'website',
    twitterCard: 'summary_large_image',
    keywords: 'pest control kochi, best pest control, termite control, cockroach control, bed bug treatment',
    robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
    h1: 'Best Pest Control Company in Kochi – 29+ Years of Trusted Service',
    breadcrumb: ['Home'],
    lastModified: '2026-08-05',
    changefreq: 'daily',
    priority: '1.0',
  },
  'pest-control-kochi': {
    title: 'Pest Control Kochi - #1 Rated Professional Service | Eco Pest India',
    description: 'Top-rated pest control in Kochi for termites, cockroaches, bed bugs & rodents. Safe, eco-friendly treatments with up to 5-year warranty. Free inspection, 4.9★ rating, 4,800+ reviews.',
    canonical: '/pest-control-kochi/',
    ogTitle: 'Best Pest Control in Kochi - Professional & Affordable Services',
    ogDescription: 'Professional pest control in Kochi with 29+ years experience. Family-safe, odorless treatments. Same-day inspections available. Call for free quote.',
    ogImage: '/images/og-pest-control-kochi.jpg',
    ogType: 'website',
    twitterCard: 'summary_large_image',
    keywords: 'pest control kochi, best pest control kochi, pest control ernakulam, pest control near me',
    robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
    h1: '#1 Professional Pest Control in Kochi | 29+ Years of Excellence',
    breadcrumb: ['Home', 'Kochi'],
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.9',
  },
  'services/termite-control': {
    title: 'Termite Control Kochi - Advanced Treatment with 5-Year Warranty',
    description: 'Professional termite control in Kochi with up to 10-year warranty. Drill-Fill-Seal technology, WHO-approved chemicals. Free inspection, 4.9★ rated service.',
    canonical: '/services/termite-control/',
    ogTitle: 'Termite Control Kochi - Best Treatment & Prevention Services',
    ogDescription: 'Advanced termite treatment in Kochi with 5-10 year warranty. Pre & post-construction services. Safe for kids & pets.',
    ogImage: '/images/og-termite-kochi.jpg',
    ogType: 'website',
    twitterCard: 'summary_large_image',
    keywords: 'termite control kochi, termite treatment kochi, drill fill seal kochi, termite prevention',
    robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
    h1: 'Termite Control Kochi - Advanced Termite Treatment & Warranty',
    breadcrumb: ['Home', 'Termite Control'],
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.85',
  },
  'locations/ernakulam': {
    title: 'Pest Control Ernakulam - #1 Trusted Service | Eco Pest India',
    description: 'Professional pest control in Ernakulam for termites, cockroaches, bed bugs & rodents. Free inspection, 5-year warranty, 4.9★ rated. Same-day service available.',
    canonical: '/locations/ernakulam/',
    ogTitle: 'Pest Control Ernakulam - Trusted Local Experts',
    ogDescription: 'Reliable pest control in Ernakulam with safe treatments and fast local response. Termite, rodent, cockroach, mosquito control.',
    ogImage: '/images/og-ernakulam.jpg',
    ogType: 'website',
    twitterCard: 'summary_large_image',
    keywords: 'pest control ernakulam, best pest control ernakulam, termite control ernakulam',
    robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
    h1: 'Pest Control Ernakulam - Trusted Local Service',
    breadcrumb: ['Home', 'Ernakulam'],
    lastModified: '2026-08-05',
    changefreq: 'weekly',
    priority: '0.8',
  },
  'blog/termite-signs-kerala': {
    title: '10 Warning Signs of Termite Infestation in Kerala Homes',
    description: 'Learn to identify termite signs in your Kerala home. Expert guide on mud tubes, hollow wood, and prevention tips from 29+ years of local experience.',
    canonical: '/blog/termite-signs-kerala/',
    ogTitle: '10 Warning Signs of Termite Infestation in Kerala Homes',
    ogDescription: 'Detect termite damage early with our Kerala-specific termite warning signs and expert prevention advice.',
    ogImage: '/images/og-termite-signs-kerala.jpg',
    ogType: 'article',
    twitterCard: 'summary_large_image',
    keywords: 'termite signs kerala, termite infestation signs, termite control kochi',
    robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
    h1: '10 Warning Signs of Termite Infestation in Kerala Homes',
    breadcrumb: ['Home', 'Blog', 'Termite Signs'],
    lastModified: '2026-08-05',
    changefreq: 'monthly',
    priority: '0.6',
  }
};

export const defaultPageData = {
  title: 'Eco Pest India - Trusted Pest Control in Kochi',
  description: 'Professional pest control services in Kochi, Ernakulam, and Kerala. Safe termite, rodent, cockroach, mosquito, and bed bug control.',
  canonical: '/',
  ogTitle: 'Eco Pest India - Trusted Pest Control',
  ogDescription: 'Eco Pest India offers safe, local pest control services in Kochi with expert technicians and transparent pricing.',
  ogImage: '/images/1.jpeg',
  ogType: 'website',
  twitterCard: 'summary_large_image',
  keywords: 'pest control kochi, pest control ernakulam, termite control',
  robots: 'index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large',
  h1: 'Eco Pest India - Trusted Pest Control in Kochi',
};
